### ISSUE TITLE
Cardinal_ZF in ROOT ?

### ISSUE THREAD

**Issue by CoghettoR** [SKolodynski/IsarMathLib#19]
Cardinal_ZF is used in the GROUP_ZF_4 theory and it appears in the pdf documents thanks to its dependency on GROUP_ZF_4. It is also used in Topology_ZF_examples

Would adding Cardinal_ZF in the ROOT file be a good idea?

**Comment by SKolodynski** [comment]
Yes, it should be there, right after `func_ZF_1` as on the isarmathlib.org site. The way it is now it shows up in the proof document in a wrong place. Thank you for pointing this out, I will correct that on the next release.
