### ISSUE TITLE
Adding issues and milestones

### ISSUE THREAD

**Issue by dan323** [SKolodynski/IsarMathLib#2]
Hello @SKolodynski,

I am wondering if we could add a list of theories or theorems you may want in the project as issues in this repo. So that everyone is in the same page. Also, just to note that my request should be merged in the next release as IsarMathlib is not executable as it is now.

Thank you,
Daniel de la Concepción Sáez

**Comment by SKolodynski** [comment]
I will list things that I am thinking about. Right now it is mostly around properties of uniform spaces. 
Or maybe one can use the list of areas Kevin Buzzard thinks are [fashionable](https://xenaproject.wordpress.com/2020/02/09/where-is-the-fashionable-mathematics/)  
But the number of things that have been formalized in IsarMathLib is so small that really anything you think about is fine.
Slawomir

**Comment by dan323** [comment]
I would also try to convince you to instanciate sublocales instead of simply proving group0(G,f) in topgroup, for example. It would make the proofs so much easier. Section 4 in https://isabelle.in.tum.de/doc/locales.pdf
