### ISSUE TITLE
Add interpretation to the parser

### ISSUE THREAD

**Issue by dan323** [SKolodynski/IsarMathLib#26]
It will be interesting to add the possibility to interpret locales with the `interpretation` key word as follows:

```isar
definition comp2 ("_{_ O _}") where
  "X{f O g} ≡ Composition(X)`⟨f,g⟩" 

interpretation comp_monoid:monoid0 "X→X" "Composition(X)" "comp2(X)"
  unfolding monoid0_def comp2_def using Group_ZF_2_5_L2(1) by auto
```

**Comment by SKolodynski** [comment]
I thought `interpretation` is supported, but indeed it's not. I will add it. Can you tell me what is the difference between `sublocale` and `interpretation`? Both seem to make theorems proven in one locale available in another one.

**Comment by dan323** [comment]
`Sublocale` interprets a locale within another locale; but `interpretation` instances a locale without another locale in context.

**Comment by SKolodynski** [comment]
I have added support for `interpretation`, tested on the above example, please check.

**Comment by dan323** [comment]
Seems fine to me

**Comment by dan323** [comment]
It was added in commit [147624f44caf8cd8dbfb22812b6392ab34b65456](https://github.com/SKolodynski/IsarMathLib/commit/147624f44caf8cd8dbfb22812b6392ab34b65456)
