### ISSUE TITLE
Possibility of CI with github actions

### ISSUE THREAD

**Issue by dan323** [SKolodynski/IsarMathLib#6]
It could be interesting to investigate if there is a way to apply some CI steps at PR creation, push to master and even publish the website at each release. I personally do not have any idea how to run Isabelle on the remote machine with github actions.

**Comment by SKolodynski** [comment]
Alexander Krauss did something like that for his [Isabelle ZF Experiments](https://github.com/alexkrauss/isabelle-zf-experiments) project using an Isabelle docker image hosted at [Circle CI](https://circleci.com/). I am not sure the time investment needed to set this up is worth it at the scale IsarMathLib operates.

**Comment by dan323** [comment]
This issue was solved by executing CI that builds the IsarMathLib and that verifies the syle with the parser
