### ISSUE TITLE
TopologicalGroup_ZF.thy HTML rendering broken for v1.12.0

### ISSUE THREAD

**Issue by SKolodynski** [SKolodynski/IsarMathLib#7]
The isar2html tool cannot parse TopologicalGroup_ZF.thy released with v1.12.0 so it can not be presented at isarmathlib.org.

**Comment by dan323** [comment]
What is the specific issue?

**Comment by SKolodynski** [comment]
There are some Isar constructs  that you are using that are not supported by isar2html parser. I don't want you to worry too much about that, so far I could always modify the proofs to not use them. In this specific case there were missing comments before theorems (isar2html enforces this) and constructs like ```group0.group0_5_L2(2)[OF group0_valid_in_tgroup, of g]``` that the isar2html parser does not accept. When I was fixing this I got some ideas on how to shorten the proofs of the lemmas you have added, you can see the changes in the commit.
